In [1]:
import pandas as pd

In [3]:
from sqlalchemy import create_engine

In [29]:
import pyarrow.dataset as ds

In [31]:
from time import time

In [2]:
df = pd.read_parquet("yellow_tripdata_2025-01.parquet")

In [5]:
df.shape

(3475226, 20)

In [7]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3475226 entries, 0 to 3475225
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[ns](2), float64(13), int32(3), int64(1), object(1)
memory usage: 490.5+ MB

In [9]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,3.475226e+06,3475226,3475226,2.935077e+06,3.475226e+06,2.935077e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,2.935077e+06,2.935077e+06,3.475226e+06
mean,1.785428e+00,2025-01-17 11:02:55.910962944,2025-01-17 11:17:56.997899776,1.297859e+00,5.855126e+00,2.482535e+00,1.651916e+02,1.641252e+02,1.036623e+00,1.708180e+01,1.317737e+00,4.780991e-01,2.959813e+00,4.493081e-01,9.547946e-01,2.561129e+01,2.225237e+00,1.239111e-01,4.834093e-01
min,1.000000e+00,2024-12-31 20:47:55,2024-12-18 07:52:40,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-9.000000e+02,-7.500000e+00,-5.000000e-01,-8.600000e+01,-1.269400e+02,-1.000000e+00,-9.010000e+02,-2.500000e+00,-1.750000e+00,-7.500000e-01
25%,2.000000e+00,2025-01-10 07:59:01,2025-01-10 08:15:29.500000,1.000000e+00,9.800000e-01,1.000000e+00,1.320000e+02,1.130000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.520000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2025-01-17 15:41:33,2025-01-17 15:59:34,1.000000e+00,1.670000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.211000e+01,0.000000e+00,5.000000e-01,2.450000e+00,0.000000e+00,1.000000e+00,1.995000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2025-01-24 19:34:06,2025-01-24 19:48:31,1.000000e+00,3.100000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,1.950000e+01,2.500000e+00,5.000000e-01,3.930000e+00,0.000000e+00,1.000000e+00,2.778000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2025-02-01 00:00:44,2025-02-01 23:44:11,9.000000e+00,2.764236e+05,9.900000e+01,2.650000e+02,2.650000e+02,5.000000e+00,8.633721e+05,1.500000e+01,1.050000e+01,4.000000e+02,1.709400e+02,1.000000e+00,8.633804e+05,2.500000e+00,6.750000e+00,7.500000e-01
std,4.263282e-01,NaN,NaN,7.507503e-01,5.646016e+02,1.163277e+01,6.452948e+01,6.940169e+01,7.013334e-01,4.634729e+02,1.861509e+00,1.374623e-01,3.779681e+00,2.002582e+00,2.781938e-01,4.636585e+02,9.039932e-01,4.725090e-01,3.619307e-01

In [10]:
df.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

## VendorID

In [12]:
df["VendorID"].value_counts()

VendorID
2    2719860
1     753671
7       1206
6        489
Name: count, dtype: int64

## Pickup and DropOff

In [13]:
df["tpep_pickup_datetime"].min(), df["tpep_pickup_datetime"].max()
df["tpep_dropoff_datetime"].min(), df["tpep_dropoff_datetime"].max()

(Timestamp('2024-12-18 07:52:40'), Timestamp('2025-02-01 23:44:11'))

## Passenger Count

In [14]:
df["passenger_count"].value_counts().sort_index()

passenger_count
0.0      24656
1.0    2322434
2.0     407761
3.0      91409
4.0      59009
5.0      17786
6.0      12004
7.0          4
8.0         11
9.0          3
Name: count, dtype: int64

## Trip Distance

In [15]:
df["trip_distance"].describe()

count    3.475226e+06
mean     5.855126e+00
std      5.646016e+02
min      0.000000e+00
25%      9.800000e-01
50%      1.670000e+00
75%      3.100000e+00
max      2.764236e+05
Name: trip_distance, dtype: float64

## RatecodeID

In [16]:
df["RatecodeID"].value_counts()

RatecodeID
1.0     2756472
2.0       94420
99.0      41963
5.0       26501
3.0        8622
4.0        7092
6.0           7
Name: count, dtype: int64

## Store and Forward

In [17]:
df["store_and_fwd_flag"].value_counts()

store_and_fwd_flag
N    2927431
Y       7646
Name: count, dtype: int64

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

## Pickup and Dropoff Location IDs

In [18]:
df["PULocationID"].nunique(), df["DOLocationID"].nunique()

(261, 260)

## Payment Type

In [19]:
df["payment_type"].value_counts()

payment_type
1    2444393
0     540149
2     390429
4      76481
3      23773
5          1
Name: count, dtype: int64

## Fares and Charges

In [20]:
fare_cols = ["fare_amount","extra","mta_tax","tip_amount","tolls_amount",
             "improvement_surcharge","total_amount","congestion_surcharge",
             "Airport_fee","cbd_congestion_fee"]

df[fare_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
fare_amount,3475226.0,17.081803,463.472918,-900.00,8.6,12.11,19.50,863372.12
extra,3475226.0,1.317737,1.861509,-7.50,0.0,0.00,2.50,15.00
mta_tax,3475226.0,0.478099,0.137462,-0.50,0.5,0.50,0.50,10.50
tip_amount,3475226.0,2.959813,3.779681,-86.00,0.0,2.45,3.93,400.00
tolls_amount,3475226.0,0.449308,2.002582,-126.94,0.0,0.00,0.00,170.94
improvement_surcharge,3475226.0,0.954795,0.278194,-1.00,1.0,1.00,1.00,1.00
total_amount,3475226.0,25.611292,463.658478,-901.00,15.2,19.95,27.78,863380.37
congestion_surcharge,2935077.0,2.225237,0.903993,-2.50,2.5,2.50,2.50,2.50
Airport_fee,2935077.0,0.123911,0.472509,-1.75,0.0,0.00,0.00,6.75
cbd_congestion_fee,3475226.0,0.483409,0.361931,-0.75,0.0,0.75,0.75,0.75

## Ingesting- getting the local dataset (loaded in Jupyter) into your Postgres DB, so pgAdmin can see it

In [23]:
engine = create_engine('postgresql://root:root@localhost:5433/ny_taxi_data')

In [24]:
#create the connection to the databse engine to see if everything is working properly

engine.connect()

In [25]:
#push the dataframe(df) into postgres

df.to_sql("ny_taxi_data", engine, if_exists="replace", index=False)

226

## Using chunks and iterator to process data

In [30]:
dataset = ds.dataset("yellow_tripdata_2025-01.parquet", format="parquet")

scanner = dataset.to_batches(batch_size=100_000)

df_iter = (batch.to_pandas() for batch in scanner)

df = next(df_iter)

In [32]:
for df in df_iter:
    t_start = time()
    df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
    t_end = time()
    print(f"inserted another chunk in {t_end - t_start:.2f} seconds")

inserted another chunk in 15.96 seconds
inserted another chunk in 14.00 seconds
inserted another chunk in 14.32 seconds
inserted another chunk in 14.21 seconds
inserted another chunk in 14.34 seconds
inserted another chunk in 14.75 seconds
inserted another chunk in 17.56 seconds
inserted another chunk in 15.53 seconds
inserted another chunk in 13.82 seconds
inserted another chunk in 6.89 seconds
inserted another chunk in 14.89 seconds
inserted another chunk in 14.83 seconds
inserted another chunk in 14.49 seconds
inserted another chunk in 14.13 seconds
inserted another chunk in 14.16 seconds
inserted another chunk in 13.69 seconds
inserted another chunk in 13.68 seconds
inserted another chunk in 14.84 seconds
inserted another chunk in 14.15 seconds
inserted another chunk in 14.45 seconds
inserted another chunk in 6.88 seconds
inserted another chunk in 15.43 seconds
inserted another chunk in 16.47 seconds
inserted another chunk in 19.51 seconds
inserted another chunk in 16.96 seconds
inserted another chunk in 16.96 seconds
inserted another chunk in 15.82 seconds
inserted another chunk in 17.29 seconds
inserted another chunk in 16.27 seconds
inserted another chunk in 15.66 seconds
inserted another chunk in 14.48 seconds
inserted another chunk in 6.81 seconds
inserted another chunk in 14.62 seconds
inserted another chunk in 14.12 seconds
inserted another chunk in 15.01 seconds
inserted another chunk in 4.60 seconds

In [33]:
## inthe above command use consisten naming ny_taxi_data instead of yellow_taxi_data

In [34]:
row_count = dataset.count_rows()
print("Total rows in parquet:", row_count)

Total rows in parquet: 3475226